"""empty message

Revision ID: dc1a954aff5a
Revises: 
Create Date: 2018-11-20 21:17:59.662934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1a954aff5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('_a_password', sa.String(length=256), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('c_u_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('p_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('cinema_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('c_name', sa.String(length=32), nullable=True),
    sa.Column('_c_password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('m_name', sa.String(length=128), nullable=True),
    sa.Column('m_name_en', sa.String(length=256), nullable=True),
    sa.Column('m_director', sa.String(length=64), nullable=True),
    sa.Column('m_leading_role', sa.String(length=256), nullable=True),
    sa.Column('m_duration', sa.Integer(), nullable=True),
    sa.Column('m_country', sa.String(length=64), nullable=True),
    sa.Column('m_type', sa.String(length=64), nullable=True),
    sa.Column('m_screen_model', sa.String(length=32), nullable=True),
    sa.Column('m_open_day', sa.DateTime(), nullable=True),
    sa.Column('m_introduce', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('p_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('c_name', sa.String(length=32), nullable=True),
    sa.Column('c_address', sa.String(length=128), nullable=True),
    sa.Column('c_phone', sa.String(length=32), nullable=True),
    sa.Column('c_city', sa.String(length=32), nullable=True),
    sa.Column('c_user', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['c_user'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('cinema_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('u_permission_id', sa.Integer(), nullable=True),
    sa.Column('u_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_permission_id'], ['c_u_permission.id'], ),
    sa.ForeignKeyConstraint(['u_user_id'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinema_user_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('c_cinema_user', sa.Integer(), nullable=True),
    sa.Column('c_movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_cinema_user'], ['cinema_user.id'], ),
    sa.ForeignKeyConstraint(['c_movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('o_user', sa.Integer(), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.Column('o_time', sa.DateTime(), nullable=True),
    sa.Column('o_movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['o_movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['o_user'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('u_permission_id', sa.Integer(), nullable=True),
    sa.Column('u_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['u_user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('h_number', sa.String(length=32), nullable=True),
    sa.Column('h_type', sa.Integer(), nullable=True),
    sa.Column('h_seats', sa.String(length=256), nullable=True),
    sa.Column('h_cinema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h_cinema'], ['cinema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    op.drop_table('user_permission')
    op.drop_table('order')
    op.drop_table('cinema_user_movie')
    op.drop_table('cinema_permission')
    op.drop_table('cinema')
    op.drop_table('permission')
    op.drop_table('movie')
    op.drop_table('cinema_user')
    op.drop_table('c_u_permission')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
